services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=42lausanne'
      - 'POSTGRES_PASSWORD=42lausanne'
      - 'POSTGRES_DB=postgres'
    volumes:
      - './volumes/quezada-dev/postgres:/var/lib/postgresql/data'
